### ISSUE TITLE
Refprop10 compilation

### ISSUE THREAD

**Issue by tajchman** [usnistgov/REFPROP-cmake#101]
Hello,

I tried to compile Refprop10 using REFPROP-cmake.

The configuration system (generate_aliases.py) complains that it could not find a file named PASS_FTN.FOR

This file is part of Refprop v9 but not Refprop 10.

Thanks in advance,
Best Regards

Marc

**Comment by ianhbell** [comment]
``PASS_FTN.FOR`` is included in REFPROP 10, but in a subfolder called ``DLLFILES``.  Please show the shell output you received and what commands you ran, impossible to debug otherwise.

**Comment by tajchman** [comment]
You're right : the configuration step tries to open os.path.join(path_to_FORTRAN,"DLLFILES","PASS_FTN.FOR) that doesn't exists in the local sources of Refprop (9 - 10)

I guess that my colleague who installed the sources, didn't copy the DLLFILES folder, as we only use Refprop in a Linux environment, and only from a C++ code (no python interface needed).

Thanks a lot for your help.

Output of cmake command :

````
mt173834@IS247798:~/Workspace/Issue5488/Refprop10$ cmake -S REFPROP-cmake -B build -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 13.2.0
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /usr/bin/gfortran - skipped
CMake Warning (dev) at CMakeLists.txt:6 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /usr/bin/python (found version "3.12.3")
-- DEFSYM_FLAG: --using-defsym
-- Alias generation output: linux

-- Alias generation error: Traceback (most recent call last):
  File "/home/mt173834/Workspace/Issue5488/Refprop10/REFPROP-cmake/generate_aliases.py", line 22, in tokenize
    for line in open(os.path.join(path_to_FORTRAN,"PASS_FTN.FOR"), 'r').readlines():
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/mt173834/Workspace/Issue5488/Refprop10/REFPROP-cmake/fortran/PASS_FTN.FOR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mt173834/Workspace/Issue5488/Refprop10/REFPROP-cmake/generate_aliases.py", line 129, in <module>
    tokens = tokenize(header_path, FORTRAN_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mt173834/Workspace/Issue5488/Refprop10/REFPROP-cmake/generate_aliases.py", line 25, in tokenize
    for line in open(os.path.join(path_to_FORTRAN,"DLLFILES","PASS_FTN.FOR"), 'r').readlines():
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/mt173834/Workspace/Issue5488/Refprop10/REFPROP-cmake/fortran/DLLFILES/PASS_FTN.FOR'

CMake Error at CMakeLists.txt:174 (file):
  file failed to open for reading (No such file or directory):

    /home/mt173834/Workspace/Issue5488/Refprop10/build/aliases_string.txt


-- Configuring incomplete, errors occurred!
````

**Comment by ianhbell** [comment]
So I guess you're sorted then, good
