### ISSUE TITLE
CoolProp inside docker build can't find the REFPROP backend

### ISSUE THREAD

**Issue by dshen109** [usnistgov/REFPROP-cmake#30]
I'm trying to build REFPROP 10 in a Docker container. The container build succeeds, and I'm able to use REFPROP in CoolProp while inside the `/opt/refprop/` folder with the copied REFPROP files, but am unable to use the REFPROP backend anywhere else inside the container. I assume this is because some path variable isn't being properly set in my build?

## Dockerfile
```Dockerfile
FROM python:3.7 as build

# Install dependencies needed to build C extensions
RUN apt-get -y -m update && \
    apt-get install -y cmake g++ gfortran python-pip

RUN pip install numpy six

WORKDIR /usr/local/refprop

# Copy in the refprop repo for building
COPY . .

# Make the default refprop location
RUN mkdir /opt/refprop

# Set path
ENV LD_LIBRARY_PATH="/opt/refprop:/usr/local/lib:/usr/local/include:$LD_LIBRARY_PATH"

WORKDIR /usr/local/refprop/build

RUN cmake .. -DREFPROP_FORTRAN_PATH=/usr/local/refprop/files/fortran -DCMAKE_BUILD_TYPE=Release && \
    cmake --build .

# copy files to the default refprop locations
COPY files/fluids /opt/refprop/fluids/
COPY files/mixtures /opt/refprop/mixtures/
RUN cp -r /usr/local/refprop/build/librefprop.so /opt/refprop/librefprop.so
RUN cp -r /usr/local/refprop/build/librefprop.so /usr/local/lib/librefprop.so
RUN cp -r /usr/local/refprop/build/librefprop.so /usr/local/include/librefprop.so

WORKDIR /usr/local/refprop/

# Used for testing, doesn't hurt anything except image size
RUN pip install coolprop
```

## To Reproduce
After successfully building the docker container, I shell into docker container using `docker run -it refprop bash` and run CoolProp using Python:

```bash

root@7c0c0eedb6d0:/usr/local/refprop# ls
CMakeLists.txt  Dockerfile  README.md  build  docker  externals  files  generate_aliases.py

root@7c0c0eedb6d0:/usr/local/refprop# python -c "from CoolProp.CoolProp import PropsSI; \
>     print(PropsSI(\"T\", \"P\", 184700, \"Q\", 1, \"REFPROP::R407A.MIX\"))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "CoolProp/CoolProp.pyx", line 347, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 427, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 314, in CoolProp.CoolProp.__Props_err2
ValueError: Initialize failed for backend: "REFPROP", fluid: "R407A.MIX" fractions "[ 1.0000000000 ]"; error: Unable to load mixture: R407A.MIX : PropsSI("T","P",184700,"Q",1,"REFPROP::R407A.MIX")

root@7c0c0eedb6d0:/usr/local/refprop# cd /opt/refprop/ && python -c "from CoolProp.CoolProp import PropsSI; \
>     print(PropsSI(\"T\", \"P\", 184700, \"Q\", 1, \"REFPROP::R407A.MIX\"))"
247.5255987356593
````

**Comment by ianhbell** [comment]
Well, the REFPROP SO is only available inside your docker container.  So outside the container it should not work I would say.  What error do you get?  The whole point of the docker container is to be running inside the docker container....  Otherwise I would just build locally if it were me.

**Comment by dshen109** [comment]
My python commands are running inside the docker container -- I'm building the container, then shelling into the container environment, and then running the CoolProp commands.

Unfortunately, our application requires us to use a containerized environment.

**Comment by ianhbell** [comment]
Correct - containerized applications are a good thing. Your python commands seem to be working inside the container, so what is the problem?

**Comment by dshen109** [comment]
My CoolProp commands only work when I'm in the `/opt/refprop` directory,  if I run CoolProp from any other directory, it gives me this error:
```python
ValueError: Initialize failed for backend: "REFPROP", fluid: "R407A.MIX" fractions "[ 1.0000000000 ]"; error: Unable to load mixture: R407A.MIX : PropsSI("T","P",184700,"Q",1,"REFPROP::R407A.MIX")
```

**Comment by ianhbell** [comment]
You need to set the REFPROP path on non-windows platforms: http://www.coolprop.org/coolprop/REFPROP.html#path-issues .  Recommend you set this up as a script rather than a command line call.

**Comment by ianhbell** [comment]
You might also want to consider using the native Python interface of REFPROP: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/python .  Plusses and minuses with CoolProp+REFPROP combination

**Comment by dshen109** [comment]
Setting the `ALTERNATIVE_REFPROP_LIBRARY_PATH` doesn't seem to be working either:

```python
>>> CP.set_config_string(CP.ALTERNATIVE_REFPROP_LIBRARY_PATH, '/opt/refprop/librefprop.so')
>>> CP.PropsSI("H", "P", 1e5, "T", 300, "REFPROP::water")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/CoolProp.pyx", line 347, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 427, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 314, in CoolProp.CoolProp.__Props_err2
ValueError: Initialize failed for backend: "REFPROP", fluid: "water" fractions "[ 1.0000000000 ]"; error: You cannot use the REFPROPMixtureBackend. : PropsSI("H","P",100000,"T",300,"REFPROP::water")
>>> CP.PropsSI("H", "P", 1e5, "T", 300, "REFPROP::water")
```

**Comment by ianhbell** [comment]
The path is to /opt/refprop (and inside that folder should be fluids and mixtures folders)

**Comment by dshen109** [comment]
That doesn't seem to work either (and actually, setting the ALTERNATIVE_REFPROP_LIBRARY_PATH seems to break the REFPROP references for pure fluids???
```
root@3b8df8a4fce3:/usr/local£ ls /opt/refprop/
fluids	librefprop.so  mixtures
```

```python
Python 3.7.2 (default, Dec 29 2018, 07:16:08) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import CoolProp.CoolProp as CP

>>> CP.PropsSI("H", "P", 1e5, "T", 300, "REFPROP::water")
112653.67968889134

>>> CP.PropsSI("H", "P", 1e5, "T", 300, "REFPROP::R407A.MIX")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/CoolProp.pyx", line 347, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 427, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 314, in CoolProp.CoolProp.__Props_err2
ValueError: Initialize failed for backend: "REFPROP", fluid: "R407A.MIX" fractions "[ 1.0000000000 ]"; error: Unable to load mixture: R407A.MIX : PropsSI("H","P",100000,"T",300,"REFPROP::R407A.MIX")

>>> CP.set_config_string(CP.ALTERNATIVE_REFPROP_LIBRARY_PATH, '/opt/refprop/')

>>> CP.PropsSI("H", "P", 1e5, "T", 300, "REFPROP::R407A.MIX")
Good news: It is possible to use REFPROP on your system! However, the library 
could not be loaded. Please make sure that REFPROP is available on your system.

Neither found in current location nor found in system PATH.
If you already obtained a copy of REFPROP from http://www.nist.gov/srd/, 
add location of REFPROP to the PATH environment variable or your library path.

In case you do not use Windows, have a look at https://github.com/jowr/librefprop.so 
to find instructions on how to compile your own version of the REFPROP library.

ALTERNATIVE_REFPROP_PATH: 
ERROR: Could not load REFPROP (/opt/refprop/) due to: /opt/refprop/: cannot read file data: Is a directory. Make sure the library is in your system search path. In case you run 64bit Windows and you have a REFPROP license, try installing the 64bit DLL from NIST. 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/CoolProp.pyx", line 347, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 427, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 314, in CoolProp.CoolProp.__Props_err2
ValueError: Initialize failed for backend: "REFPROP", fluid: "R407A.MIX" fractions "[ 1.0000000000 ]"; error: You cannot use the REFPROPMixtureBackend. : PropsSI("H","P",100000,"T",300,"REFPROP::R407A.MIX")

>>> CP.PropsSI("H", "P", 1e5, "T", 300, "REFPROP::water")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/CoolProp.pyx", line 347, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 427, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 314, in CoolProp.CoolProp.__Props_err2
ValueError: Initialize failed for backend: "REFPROP", fluid: "water" fractions "[ 1.0000000000 ]"; error: You cannot use the REFPROPMixtureBackend. : PropsSI("H","P",100000,"T",300,"REFPROP::water")
```

**Comment by ianhbell** [comment]
Are you really using REFPROP 10?  I thought maybe this was a case-sensitivity issue...  Can you copy fluids to FLUIDS and mixtures to MIXTURES? I don't remember what is expected in CoolProp.  Is there a R407A.MIX file in mixtures?

**Comment by dshen109** [comment]
- I am using version 10: `>>> CP.get_global_param_string("REFPROP_version")
'10.0'`

- There is indeed a R407A.MIX file in `mixtures`.

- Using the capitalized `FLUIDS` and `MIXTURES` folders completely breaks CoolProp.

- Also, apparently with my build refprop pure fluids work globally inside the container without any additional setup, while mixtures require the code to be executed in the `/opt/refprop` folder:
```
root@e92f6047d89e:/opt£ python
Python 3.7.2 (default, Dec 29 2018, 07:16:08) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import CoolProp.CoolProp as CP
>>> CP.PropsSI("H", "P", 1e5, "T", 300, "REFPROP::water")
112653.67968889134
>>> CP.PropsSI("H", "P", 1e5, "T", 300, "REFPROP::R407A.MIX")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/CoolProp.pyx", line 347, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 427, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 314, in CoolProp.CoolProp.__Props_err2
ValueError: Initialize failed for backend: "REFPROP", fluid: "R407A.MIX" fractions "[ 1.0000000000 ]"; error: Unable to load mixture: R407A.MIX : PropsSI("H","P",100000,"T",300,"REFPROP::R407A.MIX")
```

Are there any files that I need to move into the appropriate folders other than `fluids`, `mixtures`, and `librefprop.so` into `/opt/refprop`? I noticed my local Ubuntu16.04 machine that runs REFPROP has a `/usr/local/include/librefprop.so` file.

**Comment by ianhbell** [comment]
Can you try to enable more debugging when doing the second call to load the mixture?  It goes like: CoolProp.set_debug_level(100).  It will be rather verbose, I fear, but could get to the bottom of the problem.

**Comment by dshen109** [comment]
Here's what I get
```
>>> import CoolProp.CoolProp as CP
>>> CP.set_debug_level(100)
>>> CP.PropsSI("H", "P", 1e5, "T", 300, "REFPROP::R407A.MIX")
/io/src/CoolProp.cpp:107: backend extracted. backend: REFPROP. fluid: R407A.MIX
AbstractState::factory(REFPROP,[ R407A.MIX ])
AbstractState::factory backend_library size: 7
Initialize failed for backend: "REFPROP", fluid: "R407A.MIX" fractions "[ 1.0000000000 ]"; error: Unable to load mixture: R407A.MIX
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/CoolProp.pyx", line 347, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 427, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 314, in CoolProp.CoolProp.__Props_err2
ValueError: Initialize failed for backend: "REFPROP", fluid: "R407A.MIX" fractions "[ 1.0000000000 ]"; error: Unable to load mixture: R407A.MIX : PropsSI("H","P",100000,"T",300,"REFPROP::R407A.MIX")
>>> 
```

**Comment by dshen109** [comment]
I was able to edit the REFPROPMixtureBackend file to print out the mixture path before loading (line 334):
```
            std::string path_to_MIX_file = join_path(get_REFPROP_mixtures_path_prefix(), components_joined_raw);
            printf("%s\n\n", path_to_MIX_file.c_str());
            const char * _components_joined_raw  = path_to_MIX_file.c_str();
```

It looks like REFPROP is getting passed the appropriate path...

```
>>> CP.AbstractState("REFPROP", "R407A.MIX")
/opt/refprop/mixtures/R407A.MIX

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/AbstractState.pyx", line 32, in CoolProp.CoolProp.AbstractState.__cinit__
ValueError: Unable to load mixture: R407A.MIX
```

**Comment by dshen109** [comment]
More printing... the `SETMIXdll` function is throwing a 101 error

```
            printf("mix2 %s\n\n", mix);

            SETMIXdll(mix,
                      hmx_bnc,
                      reference_state,
                      &N,
                      component_string,
                      &(x[0]),
                      &ierr,
                      herr,
                      255,
                      255,
                      3,
                      10000,
                      255);

            printf("ierr %d\n", ierr);
```

```
>>> import CoolProp.CoolProp as CP
>>> CP.AbstractState("REFPROP", "R407A.MIX")
/opt/refprop/mixtures/R407A.MIX

_components_joined_raw /opt/refprop/mixtures/R407A.MIX

mix @�b�

mix2 /opt/refprop/mixtures/R407A.MIX

ierr 101
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/AbstractState.pyx", line 32, in CoolProp.CoolProp.AbstractState.__cinit__
ValueError: Unable to load mixture: R407A.MIX
```

**Comment by dshen109** [comment]
Looks like the inputs to the [`SETMIXdll` function](https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html#f/_/SETMIXdll) are wrong? The documentation suggests that the variable lengths `hMixNme_length` and `hFmix_length` need to be set, yet they're hardcoded as 255 here.

More printing that I did:

```
>>> CP.set_debug_level(100)
>>> CP.AbstractState("REFPROP", "water")
AbstractState::factory(REFPROP,[ water ])
AbstractState::factory backend_library size: 7
../../src/Backends/REFPROP/REFPROPMixtureBackend.cpp:441: Successfully loaded REFPROP fluid: /opt/refprop/fluids/WATER
<CoolProp.CoolProp.AbstractState object at 0x7fcb34a8eb90>
>>> CP.AbstractState("REFPROP", "R407A.MIX")
AbstractState::factory(REFPROP,[ R407A.MIX ])
AbstractState::factory backend_library size: 7
/opt/refprop/mixtures/R407A.MIX

_components_joined_raw /opt/refprop/mixtures/R407A.MIX

mix /opt/refprop/mixtures/R407A.MIX
mix length 31

hmx_bnc /opt/refprop/fluids/HMX.BNC
hmx_bnc length 27

ierr 101
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/AbstractState.pyx", line 32, in CoolProp.CoolProp.AbstractState.__cinit__
ValueError: Unable to load mixture: R407A.MIX
```

**Comment by ianhbell** [comment]
Here's the core bug report: https://github.com/usnistgov/REFPROP-issues/issues/168

**Comment by ianhbell** [comment]
This works now with the Dockerfile from https://github.com/usnistgov/REFPROP-tests/blob/c69aa868d055e249f6daef298f4aef9c4578fabf/docker/gcov/Dockerfile 

We made some updates to core of REFPROP, please inquire about a beta you can try.

```python
import CoolProp.CoolProp as CP
CP.set_config_string(CP.ALTERNATIVE_REFPROP_PATH, "/REFPROP-cmake/build")
CP.set_debug_level(100)
CP.AbstractState("REFPROP", "WATER")
CP.AbstractState("REFPROP", "R407A.MIX")
```
yields
```
root@4acdfbd0ad9a:/REFPROP-cmake/build# python3 t.py
AbstractState::factory(REFPROP,[ WATER ])
AbstractState::factory backend_library size: 7
/io/src/Backends/REFPROP/REFPROPMixtureBackend.cpp:429: Successfully loaded REFPROP fluid: /REFPROP-cmake/build/fluids/WATER
AbstractState::factory(REFPROP,[ R407A.MIX ])
AbstractState::factory backend_library size: 7
/io/src/Backends/REFPROP/REFPROPMixtureBackend.cpp:360: Successfully loaded REFPROP fluid: R407A.MIX

```
