### ISSUE TITLE
cmake build fails using numpy >1.15.4

### ISSUE THREAD

**Issue by hopalonghopper** [usnistgov/REFPROP-cmake#32]
When trying to build the REFPROP .dylib I get the error shown below. The build completes successfully using numpy <= 1.15.4.

Shell output:
```
cmake --build .

Scanning dependencies of target REFPROP_H
[  3%] About to build the REFPROP.h header file w/ /Users/jhopper2/opt/anaconda3/bin/python;-u;/Users/jhopper2/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/Users/jhopper2/REFPROP-cmake/build/FORTRAN_temp;--python-exe;/Users/jhopper2/opt/anaconda3/bin/python
Writing the .pyf file with numpy.f2py, please be patient...
Traceback (most recent call last):
  File "/Users/jhopper2/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 176, in <module>
    generate_interface_file(os.path.join(args.FORTRAN_path[0],'PASS_FTN.FOR'), 'REFPROP.pyf', python_exe = args.python_exe[0])
  File "/Users/jhopper2/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 24, in generate_interface_file
    raise ValueError('Unable to call f2py successfully: '+str(err))
ValueError: Unable to call f2py successfully: b'Traceback (most recent call last):\n  File "/Users/jhopper2/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main\n    "__main__", mod_spec)\n  File "/Users/jhopper2/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n  File "/Users/jhopper2/opt/anaconda3/lib/python3.7/site-packages/numpy/f2py/__main__.py", line 6, in <module>\n    main()\n  File "/Users/jhopper2/opt/anaconda3/lib/python3.7/site-packages/numpy/f2py/f2py2e.py", line 685, in main\n    run_main(sys.argv[1:])\n  File "/Users/jhopper2/opt/anaconda3/lib/python3.7/site-packages/numpy/f2py/f2py2e.py", line 425, in run_main\n    postlist = callcrackfortran(files, options)\n  File "/Users/jhopper2/opt/anaconda3/lib/python3.7/site-packages/numpy/f2py/f2py2e.py", line 330, in callcrackfortran\n    postlist = crackfortran.crackfortran(files)\n  File "/Users/jhopper2/opt/anaconda3/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 3265, in crackfortran\n    readfortrancode(files, crackline)\n  File "/Users/jhopper2/opt/anaconda3/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 495, in readfortrancode\n    readfortrancode(fn1, dowithline=dowithline, istop=0)\n  File "/Users/jhopper2/opt/anaconda3/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 501, in readfortrancode\n    dowithline(finalline)\n  File "/Users/jhopper2/opt/anaconda3/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 796, in crackline\n    analyzeline(m, pat[1], line)\n  File "/Users/jhopper2/opt/anaconda3/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 1184, in analyzeline\n    for e in markoutercomma(ll).split(\'@,@\'):\n  File "/Users/jhopper2/opt/anaconda3/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 833, in markoutercomma\n    assert not f, repr((f, line, l))\nAssertionError: (-1, \'ncmax=20)     !max number of components in mixtur\', \'ncmax=20)     !max number of components in mixtur\')\n'
make[2]: *** [REFPROP.h.stamp] Error 1
make[1]: *** [CMakeFiles/REFPROP_H.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by hopalonghopper** [comment]
I forgot to note that this is using homebrew gfortran

**Comment by ianhbell** [comment]
Hmmm, this seems like a bug in f2py, it's rather fragile in my experience.  Maybe I need to do some pre-processing to remove comments.  I can test on my OSX, I'll find a solution.

**Comment by ianhbell** [comment]
What version of numpy did you use? I can get builds to work in 1.17.3, I'm putting together some examples of this in docker containers

**Comment by hopalonghopper** [comment]
I believe it was 1.17.2 as when I remove numpy (in conda) and reinstall, that is the version that is installed

**Comment by ianhbell** [comment]
Can you try pip installation of numpy?  Currently that is giving 1.17.3:

![image](https://user-images.githubusercontent.com/11966765/67886099-7aced500-fb0e-11e9-8b62-1594a6e6a5bc.png)

**Comment by hopalonghopper** [comment]
I get the following error:
```
[  3%] About to build the REFPROP.h header file w/ /Users/jhopper2/opt/anaconda3/envs/test2/bin/python;-u;/Users/jhopper2/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/Users/jhopper2/REFPROP-cmake/build/FORTRAN_temp;--python-exe;/Users/jhopper2/opt/anaconda3/envs/test2/bin/python
Writing the .pyf file with numpy.f2py, please be patient...
Traceback (most recent call last):
  File "/Users/jhopper2/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 176, in <module>
    generate_interface_file(os.path.join(args.FORTRAN_path[0],'PASS_FTN.FOR'), 'REFPROP.pyf', python_exe = args.python_exe[0])
  File "/Users/jhopper2/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 24, in generate_interface_file
    raise ValueError('Unable to call f2py successfully: '+str(err))
ValueError: Unable to call f2py successfully: b'Traceback (most recent call last):\n  File "/Users/jhopper2/opt/anaconda3/envs/test2/lib/python3.7/runpy.py", line 193, in _run_module_as_main\n    "__main__", mod_spec)\n  File "/Users/jhopper2/opt/anaconda3/envs/test2/lib/python3.7/runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n  File "/Users/jhopper2/opt/anaconda3/envs/test2/lib/python3.7/site-packages/numpy/f2py/__main__.py", line 6, in <module>\n    main()\n  File "/Users/jhopper2/opt/anaconda3/envs/test2/lib/python3.7/site-packages/numpy/f2py/f2py2e.py", line 685, in main\n    run_main(sys.argv[1:])\n  File "/Users/jhopper2/opt/anaconda3/envs/test2/lib/python3.7/site-packages/numpy/f2py/f2py2e.py", line 425, in run_main\n    postlist = callcrackfortran(files, options)\n  File "/Users/jhopper2/opt/anaconda3/envs/test2/lib/python3.7/site-packages/numpy/f2py/f2py2e.py", line 330, in callcrackfortran\n    postlist = crackfortran.crackfortran(files)\n  File "/Users/jhopper2/opt/anaconda3/envs/test2/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 3251, in crackfortran\n    readfortrancode(files, crackline)\n  File "/Users/jhopper2/opt/anaconda3/envs/test2/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 495, in readfortrancode\n    readfortrancode(fn1, dowithline=dowithline, istop=0)\n  File "/Users/jhopper2/opt/anaconda3/envs/test2/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 501, in readfortrancode\n    dowithline(finalline)\n  File "/Users/jhopper2/opt/anaconda3/envs/test2/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 796, in crackline\n    analyzeline(m, pat[1], line)\n  File "/Users/jhopper2/opt/anaconda3/envs/test2/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 1184, in analyzeline\n    for e in markoutercomma(ll).split(\'@,@\'):\n  File "/Users/jhopper2/opt/anaconda3/envs/test2/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 833, in markoutercomma\n    assert not f, repr((f, line, l))\nAssertionError: (-1, \'ncmax=20)     !max number of components in mixtur\', \'ncmax=20)     !max number of components in mixtur\')\n'
make[2]: *** [REFPROP.h.stamp] Error 1
make[1]: *** [CMakeFiles/REFPROP_H.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ianhbell** [comment]
Nah, that's a "very cool" way to do it, only issue is that it works fine for me :) .  I'll have to fire up my OSX box, maybe it is something particular there.

Can you try with python 3.6?  That combo worked for me, and is what I was testing on linux.

**Comment by hopalonghopper** [comment]
same thing i believe
```
[  3%] About to build the REFPROP.h header file w/ /Users/jhopper2/opt/anaconda3/envs/test4/bin/python;-u;/Users/jhopper2/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/Users/jhopper2/REFPROP-cmake/build/FORTRAN_temp;--python-exe;/Users/jhopper2/opt/anaconda3/envs/test4/bin/python
Writing the .pyf file with numpy.f2py, please be patient...
Traceback (most recent call last):
  File "/Users/jhopper2/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 176, in <module>
    generate_interface_file(os.path.join(args.FORTRAN_path[0],'PASS_FTN.FOR'), 'REFPROP.pyf', python_exe = args.python_exe[0])
  File "/Users/jhopper2/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 24, in generate_interface_file
    raise ValueError('Unable to call f2py successfully: '+str(err))
ValueError: Unable to call f2py successfully: b'Traceback (most recent call last):\n  File "/Users/jhopper2/opt/anaconda3/envs/test4/lib/python3.6/runpy.py", line 193, in _run_module_as_main\n    "__main__", mod_spec)\n  File "/Users/jhopper2/opt/anaconda3/envs/test4/lib/python3.6/runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n  File "/Users/jhopper2/opt/anaconda3/envs/test4/lib/python3.6/site-packages/numpy/f2py/__main__.py", line 6, in <module>\n    main()\n  File "/Users/jhopper2/opt/anaconda3/envs/test4/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 685, in main\n    run_main(sys.argv[1:])\n  File "/Users/jhopper2/opt/anaconda3/envs/test4/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 425, in run_main\n    postlist = callcrackfortran(files, options)\n  File "/Users/jhopper2/opt/anaconda3/envs/test4/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 330, in callcrackfortran\n    postlist = crackfortran.crackfortran(files)\n  File "/Users/jhopper2/opt/anaconda3/envs/test4/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 3251, in crackfortran\n    readfortrancode(files, crackline)\n  File "/Users/jhopper2/opt/anaconda3/envs/test4/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 495, in readfortrancode\n    readfortrancode(fn1, dowithline=dowithline, istop=0)\n  File "/Users/jhopper2/opt/anaconda3/envs/test4/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 501, in readfortrancode\n    dowithline(finalline)\n  File "/Users/jhopper2/opt/anaconda3/envs/test4/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 796, in crackline\n    analyzeline(m, pat[1], line)\n  File "/Users/jhopper2/opt/anaconda3/envs/test4/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 1184, in analyzeline\n    for e in markoutercomma(ll).split(\'@,@\'):\n  File "/Users/jhopper2/opt/anaconda3/envs/test4/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 833, in markoutercomma\n    assert not f, repr((f, line, l))\nAssertionError: (-1, \'ncmax=20)     !max number of components in mixtur\', \'ncmax=20)     !max number of components in mixtur\')\n'
make[2]: *** [REFPROP.h.stamp] Error 1
make[1]: *** [CMakeFiles/REFPROP_H.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ianhbell** [comment]
Sure seems that way...

**Comment by ianhbell** [comment]
Time to fire up the OSX box.  Watch this space.

**Comment by ianhbell** [comment]
Unfortunately, it works totally fine for me with numpy 1.17.2 on OSX 10.14.

**Comment by ianhbell** [comment]
My build log (this is with the beta, but same results with 10.0.0)
```

$ cmake .. -DREFPROP_FORTRAN_PATH=/Users/ihb/Desktop/FORTRAN
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 7.1.0
-- Checking whether Fortran compiler has -isysroot
-- Checking whether Fortran compiler has -isysroot - yes
-- Checking whether Fortran compiler supports OSX deployment target flag
-- Checking whether Fortran compiler supports OSX deployment target flag - yes
-- Check for working Fortran compiler: /usr/local/bin/gfortran
-- Check for working Fortran compiler: /usr/local/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/local/bin/gfortran supports Fortran 90
-- Checking whether /usr/local/bin/gfortran supports Fortran 90 -- yes
-- Found PythonInterp: //anaconda/envs/py36/bin/python (found version "3.6") 
-- DEFSYM_FLAG: 
-- darwin
Missing from PASS_CMN_tokens:  []
Missing from REFPROP_lib.h: ['FNCRPTdll', 'VIRTAUdll']

-- Path to libquadmath.a:/usr/local/Cellar/gcc/7.1.0/lib/gcc/7/gcc/x86_64-apple-darwin16.6.0/7.1.0/../../../libquadmath.a
-- Copied libquadmath.a here.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/ihb/Code/REFPROP-cmake/bld
$ cmake --build .
Scanning dependencies of target REFPROP_H
[  6%] About to build the REFPROP.h header file w/ //anaconda/envs/py36/bin/python;-u;/Users/ihb/Code/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/Users/ihb/Desktop/FORTRAN;--python-exe;//anaconda/envs/py36/bin/python
Writing the .pyf file with numpy.f2py, please be patient...
About to run: //anaconda/envs/py36/bin/python -m numpy.f2py --quiet --no-lower -h REFPROP.pyf /Users/ihb/Desktop/FORTRAN/PASS_FTN.FOR
numpy version: 1.17.2
Deleting REFPROP.pyf
[  6%] Built target REFPROP_H
Scanning dependencies of target refprop
[ 12%] Building Fortran object CMakeFiles/refprop.dir/Users/ihb/Desktop/FORTRAN/CORE_ANC.FOR.o
[ 18%] Building Fortran object CMakeFiles/refprop.dir/Users/ihb/Desktop/FORTRAN/CORE_FEQ.FOR.o
[ 25%] Building Fortran object CMakeFiles/refprop.dir/Users/ihb/Desktop/FORTRAN/CORE_PR.FOR.o
[ 31%] Building Fortran object CMakeFiles/refprop.dir/Users/ihb/Desktop/FORTRAN/FLSH_SUB.FOR.o
[ 37%] Building Fortran object CMakeFiles/refprop.dir/Users/ihb/Desktop/FORTRAN/MIX_HMX.FOR.o
[ 43%] Building Fortran object CMakeFiles/refprop.dir/Users/ihb/Desktop/FORTRAN/PASS_FTN.FOR.o
[ 50%] Building Fortran object CMakeFiles/refprop.dir/Users/ihb/Desktop/FORTRAN/PROP_SUB.FOR.o
[ 56%] Building Fortran object CMakeFiles/refprop.dir/Users/ihb/Desktop/FORTRAN/REFPROP.FOR.o
/Users/ihb/Desktop/FORTRAN/REFPROP.FOR:5684:72:

          if (ABS(iErrPrnt).eq.3) pause           !If your compiler complains about this line, just delete it.
                                                                        1
Warning: Deleted feature: PAUSE statement at (1)
[ 62%] Building Fortran object CMakeFiles/refprop.dir/Users/ihb/Desktop/FORTRAN/SAT_SUB.FOR.o
[ 68%] Building Fortran object CMakeFiles/refprop.dir/Users/ihb/Desktop/FORTRAN/SETUP.FOR.o
[ 75%] Building Fortran object CMakeFiles/refprop.dir/Users/ihb/Desktop/FORTRAN/TRNSP.FOR.o
[ 81%] Building Fortran object CMakeFiles/refprop.dir/Users/ihb/Desktop/FORTRAN/TRNS_TCX.FOR.o
[ 87%] Building Fortran object CMakeFiles/refprop.dir/Users/ihb/Desktop/FORTRAN/TRNS_VIS.FOR.o
[ 93%] Building Fortran object CMakeFiles/refprop.dir/Users/ihb/Desktop/FORTRAN/UTILITY.FOR.o
[100%] Linking Fortran shared library librefprop.dylib
[100%] Built target refprop
```

**Comment by ianhbell** [comment]
My guess is that your setup is still calling your old numpy, can you please do something similar to my log so we can be sure?

**Comment by hopalonghopper** [comment]
```
$ cmake .. -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 9.2.0
-- Checking whether Fortran compiler has -isysroot
-- Checking whether Fortran compiler has -isysroot - yes
-- Checking whether Fortran compiler supports OSX deployment target flag
-- Checking whether Fortran compiler supports OSX deployment target flag - yes
-- Check for working Fortran compiler: /usr/local/bin/gfortran
-- Check for working Fortran compiler: /usr/local/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/local/bin/gfortran supports Fortran 90
-- Checking whether /usr/local/bin/gfortran supports Fortran 90 -- yes
-- Found PythonInterp: /Users/jhopper2/opt/anaconda3/envs/py36/bin/python (found version "3.6.9") 
-- DEFSYM_FLAG: 
-- darwin
Missing from PASS_CMN_tokens:  ['ABFLSHdll', 'ALLPROPS0dll', 'ALLPROPS1dll', 'ALLPROPS20dll', 'ALLPROPSdll', 'CRTPNTdll', 'DEFL1dll', 'DERVPVTdll', 'DHFL1dll', 'DSD1dll', 'ERRMSGdll', 'FLAGSdll', 'GERG08dll', 'GETENUMdll', 'GETMODdll', 'GETREFDIRdll', 'HEATFRMdll', 'HMXORDERdll', 'HSFL1dll', 'MASSFLUXdll', 'MELTKdll', 'PASSCMNdll', 'PEFL1dll', 'PHI0dll', 'PHIDERVdll', 'PHIHMXdll', 'PHIKdll', 'PHIMIXdll', 'RDXHMXdll', 'REFPROP1dll', 'REFPROP2dll', 'REFPROPdll', 'RIEMdll', 'SATESTdll', 'SATGUESSdll', 'SETFLUIDSdll', 'SETMIXTUREdll', 'SETREFDIRdll', 'STNdll', 'TEFL1dll', 'THFL1dll', 'TSATPdll', 'TSFL1dll', 'VIRBCDdll', 'WMOLIdll']
Missing from REFPROP_lib.h: ['DPDDKdll', 'DPDTKdll', 'ACTVYdll', 'DOTFILLdll', 'OMEGAdll', 'ETAK0dll', 'ETAK1dll', 'ETAKRdll', 'ETAKBdll', 'TCXK0dll', 'TCXKBdll', 'TCXKCdll']

-- Path to libquadmath.a:/usr/local/Cellar/gcc/9.2.0_1/lib/gcc/9/gcc/x86_64-apple-darwin18/9.2.0/../../../libquadmath.a
-- Copied libquadmath.a here.
-- REFPROP version <= 9.1 identified by presence of include "'commons.for'"; copying locally and fixing include statement
-- Fixing of FORTRAN files complete. Compilation ready.
-- Set REFPROP_FORTRAN_PATH to /Users/jhopper2/REFPROP-cmake/build/FORTRAN_temp
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jhopper2/REFPROP-cmake/build

$ cmake --build .
Scanning dependencies of target REFPROP_H
[  3%] About to build the REFPROP.h header file w/ /Users/jhopper2/opt/anaconda3/envs/py36/bin/python;-u;/Users/jhopper2/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/Users/jhopper2/REFPROP-cmake/build/FORTRAN_temp;--python-exe;/Users/jhopper2/opt/anaconda3/envs/py36/bin/python
Writing the .pyf file with numpy.f2py, please be patient...
About to run: /Users/jhopper2/opt/anaconda3/envs/py36/bin/python -m numpy.f2py --quiet --no-lower -h REFPROP.pyf /Users/jhopper2/REFPROP-cmake/build/FORTRAN_temp/PASS_FTN.FOR
numpy version: 1.17.2
Writing the .pyf file with numpy.f2py, please be patient...
About to run: /Users/jhopper2/opt/anaconda3/envs/py36/bin/python -m numpy.f2py --quiet --no-lower -h REFPROP.pyf /Users/jhopper2/REFPROP-cmake/build/FORTRAN_temp/DLLFILES/PASS_FTN.FOR
numpy version: 1.17.2
Traceback (most recent call last):
  File "/Users/jhopper2/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 179, in <module>
    generate_interface_file(os.path.join(args.FORTRAN_path[0],'PASS_FTN.FOR'), 'REFPROP.pyf', python_exe = args.python_exe[0])
  File "/Users/jhopper2/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 26, in generate_interface_file
    raise ValueError('Unable to call f2py successfully: '+str(err))
ValueError: Unable to call f2py successfully: b'Traceback (most recent call last):\n  File "/Users/jhopper2/opt/anaconda3/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main\n    "__main__", mod_spec)\n  File "/Users/jhopper2/opt/anaconda3/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n  File "/Users/jhopper2/opt/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/f2py/__main__.py", line 6, in <module>\n    main()\n  File "/Users/jhopper2/opt/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 685, in main\n    run_main(sys.argv[1:])\n  File "/Users/jhopper2/opt/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 425, in run_main\n    postlist = callcrackfortran(files, options)\n  File "/Users/jhopper2/opt/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/f2py/f2py2e.py", line 330, in callcrackfortran\n    postlist = crackfortran.crackfortran(files)\n  File "/Users/jhopper2/opt/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 3265, in crackfortran\n    readfortrancode(files, crackline)\n  File "/Users/jhopper2/opt/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 495, in readfortrancode\n    readfortrancode(fn1, dowithline=dowithline, istop=0)\n  File "/Users/jhopper2/opt/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 501, in readfortrancode\n    dowithline(finalline)\n  File "/Users/jhopper2/opt/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 796, in crackline\n    analyzeline(m, pat[1], line)\n  File "/Users/jhopper2/opt/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 1184, in analyzeline\n    for e in markoutercomma(ll).split(\'@,@\'):\n  File "/Users/jhopper2/opt/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/f2py/crackfortran.py", line 833, in markoutercomma\n    assert not f, repr((f, line, l))\nAssertionError: (-1, \'ncmax=20)     !max number of components in mixtur\', \'ncmax=20)     !max number of components in mixtur\')\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jhopper2/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 181, in <module>
    generate_interface_file(os.path.join(args.FORTRAN_path[0],'DLLFILES','PASS_FTN.FOR'), 'REFPROP.pyf', python_exe = args.python_exe[0])
  File "/Users/jhopper2/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 26, in generate_interface_file
    raise ValueError('Unable to call f2py successfully: '+str(err))
ValueError: Unable to call f2py successfully: b'IOError: [Errno 2] No such file or directory: \'/Users/jhopper2/REFPROP-cmake/build/FORTRAN_temp/DLLFILES/PASS_FTN.FOR\'. Skipping file "/Users/jhopper2/REFPROP-cmake/build/FORTRAN_temp/DLLFILES/PASS_FTN.FOR".\n'
make[2]: *** [REFPROP.h.stamp] Error 1
make[1]: *** [CMakeFiles/REFPROP_H.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ianhbell** [comment]
Aha, you're using an old version of REFPROP, looks like older than 9.0.  Not sure why that is precisely a problem, but it's a problem nonetheless.

**Comment by hopalonghopper** [comment]
man...I had no idea I was using an old fortran folder; i sincerely apologize for leading us down this path. I just found out we have version 10 here, installed it & pulled the fortran files over, and all is well. So sorry man but appreciate all the help!

**Comment by ianhbell** [comment]
No problem at all, glad to hear we're sorted now.  That's why I always insist on build logs, I can see these problems in seconds.

**Comment by ianhbell** [comment]
Go ahead and close the issue I think.

**Comment by ianhbell** [comment]
Also, definitely recommend you use the REFPROP_FORTRAN_PATH option, makes this problem less (though not impossible) likely.
