### ISSUE TITLE
Refprop 10 SUSE Linux Enterprise Installation issue

### ISSUE THREAD

**Issue by zenasc** [usnistgov/REFPROP-cmake#33]
New to installing Refprop 10 on SUSE Linux.

Ran 
```
cmake .. -DCMAKE_BUILD_TYPE=Release
``` 

and encountered this: (tail result)
```
/opt/REFPROP-cmake-master/build # cmake .. -DCMAKE_BUILD_TYPE=Release

CMake Error at CMakeLists.txt:263 (string):
  string does not recognize sub-command FIND


CMake Warning at CMakeLists.txt:264 (if):
  given arguments:

    "GREATER" "0"

  Unknown arguments specified


CMake Error at CMakeLists.txt:267 (string):
  string does not recognize sub-command FIND


CMake Warning at CMakeLists.txt:268 (if):
  given arguments:

    "GREATER" "0"

  Unknown arguments specified


CMake Error at CMakeLists.txt:284 (target_include_directories):
  Unknown CMake command "target_include_directories".


-- Configuring incomplete, errors occurred!
```

Then ran ```cmake --build . ``` and got: 
```
/opt/REFPROP-cmake-master/build # cmake --build .
gmake: *** No targets specified and no makefile found.  Stop.
```
Pre-requisites have been installed:
•	Python + numpy 1.8.0.3
•	Cmake 2.8.3
•	Git 2.12.3
•	Gfortran 4.8.5

Also, ```fortran``` directory retrieved from Refprop 10 folder and copied to root of ```REFPROP-cmake-master```

**Comment by ianhbell** [comment]
I bumped the required version of cmake: https://github.com/usnistgov/REFPROP-cmake/commit/68375675213b39c9ec7356c3c737d96c1144bf35 . Doesn't fix your problem (yet), but the reason for failure is at least more clear.

**Comment by zenasc** [comment]
SUSE 12.3

I will install cmake 3.x and provide results!

Thank you, sir!

**Comment by ianhbell** [comment]
Yes, please let me know.  I think it should work once cmake is upgraded.  At least I hope so.

**Comment by zenasc** [comment]
Ian,

Cmake 3.15.5 was installed and these were the results:

```
/opt/REFPROP-cmake-master/build # cmake .. -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 4.8.5
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Found PythonInterp: /usr/bin/python (found version "2.7.13") 
-- DEFSYM_FLAG: --using-defsym
-- linux2
Traceback (most recent call last):
  File "/opt/REFPROP-cmake-master/generate_aliases.py", line 129, in <module>
    tokens = tokenize(header_path, FORTRAN_path)
  File "/opt/REFPROP-cmake-master/generate_aliases.py", line 28, in tokenize
    with open(path_to_REFPROP_lib_h, 'r') as fp:
IOError: [Errno 2] No such file or directory: '/opt/REFPROP-cmake-master/externals/REFPROP-headers/REFPROP_lib.h'

CMake Error at CMakeLists.txt:148 (file):
  file failed to open for reading (No such file or directory):

    /opt/REFPROP-cmake-master/build/aliases_string.txt


-- REFPROP version <= 9.1 identified by presence of include "'commons.for'"; copying locally and fixing include statement
-- Fixing of FORTRAN files complete. Compilation ready.
-- Set REFPROP_FORTRAN_PATH to /opt/REFPROP-cmake-master/build/FORTRAN_temp
-- Configuring incomplete, errors occurred!
See also "/opt/REFPROP-cmake-master/build/CMakeFiles/CMakeOutput.log".

/opt/REFPROP-cmake-master/build # cmake --build .
gmake: *** No targets specified and no makefile found.  Stop.
```

It seems it's missing some files. Should I transfer the files from 9.1?

**Comment by ianhbell** [comment]
Couple of things:

1. Looks like you are not actually using your REFPROP 10 code, as evidenced by this line in the log:
```
REFPROP version <= 9.1 identified by presence of include "'commons.for'"; copying locally and fixing include statement
```
Recommend to use the ``-DREFPROP_FORTRAN_PATH=/path/to/fortran`` variant to point to REFPROP sources
2. To fix compilation, you need to make sure that your initial clone is recursive : https://github.com/usnistgov/REFPROP-cmake#instructions (step 1).  To fix now, do a ``git submodule update --init``

**Comment by zenasc** [comment]
After switching to the Refprop 10 code and recursive clone, these were the results:

```
/opt/REFPROP-cmake/build # cmake .. -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 4.8.5
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Found PythonInterp: /usr/bin/python (found version "2.7.13") 
-- DEFSYM_FLAG: --using-defsym
-- linux2
Missing from PASS_CMN_tokens:  []
Missing from REFPROP_lib.h: []

-- Configuring done
-- Generating done
-- Build files have been written to: /opt/REFPROP-cmake/build
```

```
/opt/REFPROP-cmake/build # cmake --build .
Scanning dependencies of target refprop
[  6%] Building Fortran object CMakeFiles/refprop.dir/fortran/CORE_ANC.FOR.o
[ 12%] Building Fortran object CMakeFiles/refprop.dir/fortran/CORE_FEQ.FOR.o
[ 18%] Building Fortran object CMakeFiles/refprop.dir/fortran/CORE_PR.FOR.o
[ 25%] Building Fortran object CMakeFiles/refprop.dir/fortran/FLSH_SUB.FOR.o
[ 31%] Building Fortran object CMakeFiles/refprop.dir/fortran/MIX_HMX.FOR.o
[ 37%] Building Fortran object CMakeFiles/refprop.dir/fortran/PROP_SUB.FOR.o
[ 43%] Building Fortran object CMakeFiles/refprop.dir/fortran/REFPROP.FOR.o
/opt/REFPROP-cmake/fortran/REFPROP.FOR:5589.72:

         if (ABS(iErrPrnt).eq.3) pause           !If your compiler compl
                                                                        1
Warning: Deleted feature: PAUSE statement at (1)
[ 50%] Building Fortran object CMakeFiles/refprop.dir/fortran/SAT_SUB.FOR.o
[ 56%] Building Fortran object CMakeFiles/refprop.dir/fortran/SETUP.FOR.o
[ 62%] Building Fortran object CMakeFiles/refprop.dir/fortran/TRNSP.FOR.o
[ 68%] Building Fortran object CMakeFiles/refprop.dir/fortran/TRNS_TCX.FOR.o
[ 75%] Building Fortran object CMakeFiles/refprop.dir/fortran/TRNS_VIS.FOR.o
[ 81%] Building Fortran object CMakeFiles/refprop.dir/fortran/UTILITY.FOR.o
[ 87%] Building Fortran object CMakeFiles/refprop.dir/fortran/DLLFILES/PASS_FTN.FOR.o
[ 93%] Linking Fortran shared library librefprop.so
[ 93%] Built target refprop
Scanning dependencies of target REFPROP_H
[100%] About to build the REFPROP.h header file w/ /usr/bin/python;-u;/opt/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/opt/REFPROP-cmake/fortran/DLLFILES;--python-exe;/usr/bin/python
Writing the .pyf file with numpy.f2py, please be patient...
About to run: /usr/bin/python -m numpy.f2py --quiet --no-lower -h REFPROP.pyf /opt/REFPROP-cmake/fortran/DLLFILES/PASS_FTN.FOR
numpy version: 1.8.0
Writing the .pyf file with numpy.f2py, please be patient...
About to run: /usr/bin/python -m numpy.f2py --quiet --no-lower -h REFPROP.pyf /opt/REFPROP-cmake/fortran/DLLFILES/DLLFILES/PASS_FTN.FOR
numpy version: 1.8.0
Traceback (most recent call last):
  File "/opt/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 181, in <module>
    generate_interface_file(os.path.join(args.FORTRAN_path[0],'DLLFILES','PASS_FTN.FOR'), 'REFPROP.pyf', python_exe = args.python_exe[0])
  File "/opt/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 26, in generate_interface_file
    raise ValueError('Unable to call f2py successfully: '+str(err))
ValueError: Unable to call f2py successfully: /usr/bin/python: No module named numpy.f2py.__main__; 'numpy.f2py' is a package and cannot be directly executed

CMakeFiles/REFPROP_H.dir/build.make:60: recipe for target 'REFPROP.h.stamp' failed
gmake[2]: *** [REFPROP.h.stamp] Error 1
CMakeFiles/Makefile2:108: recipe for target 'CMakeFiles/REFPROP_H.dir/all' failed
gmake[1]: *** [CMakeFiles/REFPROP_H.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
gmake: *** [all] Error 2
```

**Comment by ianhbell** [comment]
Your numpy version is pretty old...  But it's not crucial, so if you don't care about the REFPROP.h header, then you can just also set the ``-DREFPROP_NO_NUMPY=ON`` flag; see https://github.com/usnistgov/REFPROP-cmake#general-notes

**Comment by zenasc** [comment]
Understood. I'll get a more updated numpy version installed and run it again. Thank you for your assistance in getting this installed, Mr. Bell!

**Comment by ianhbell** [comment]
Unless you are calling from MATLAB, I wouldn't sweat it and just disable the header generation.

**Comment by zenasc** [comment]
Apparently, we will be calling from MATLAB so we'll need to update our numpy.

**Comment by ianhbell** [comment]
Too bad, that introduces a lot of interesting challenges, make sure you use the Python->MATLAB interface.

**Comment by zenasc** [comment]
It's just another bump in the road! Thanks again for your help. Will reach out with results.

**Comment by ianhbell** [comment]
How did you get on?

**Comment by zenasc** [comment]
Thank you for following up. It's true when you said that it will introduce a lot of interesting challenges:

I've updated our numpy to version 1.11.1 in python3.4

```
#pip show numpy             
Name: numpy
Version: 1.11.1
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: NumPy Developers
Author-email: numpy-discussion@scipy.org
License: BSD
Location: /usr/lib64/python3.4/site-packages
```

but it seems that when running ```cmake --build . ```  it will still use the old numpy 1.8.0 version in python2.7

```
# cmake --build .
[ 93%] Built target refprop
[100%] About to build the REFPROP.h header file w/ /usr/bin/python;-u;/opt/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/opt/REFPROP-cmake/fortran/DLLFILES;--python-exe;/usr/bin/python
Writing the .pyf file with numpy.f2py, please be patient...
About to run: /usr/bin/python -m numpy.f2py --quiet --no-lower -h REFPROP.pyf /opt/REFPROP-cmake/fortran/DLLFILES/PASS_FTN.FOR
numpy version: 1.8.0
Writing the .pyf file with numpy.f2py, please be patient...
About to run: /usr/bin/python -m numpy.f2py --quiet --no-lower -h REFPROP.pyf /opt/REFPROP-cmake/fortran/DLLFILES/DLLFILES/PASS_FTN.FOR
numpy version: 1.8.0
Traceback (most recent call last):
  File "/opt/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 181, in <module>
    generate_interface_file(os.path.join(args.FORTRAN_path[0],'DLLFILES','PASS_FTN.FOR'), 'REFPROP.pyf', python_exe = args.python_exe[0])
  File "/opt/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 26, in generate_interface_file
    raise ValueError('Unable to call f2py successfully: '+str(err))
ValueError: Unable to call f2py successfully: /usr/bin/python: No module named numpy.f2py.__main__; 'numpy.f2py' is a package and cannot be directly executed

CMakeFiles/REFPROP_H.dir/build.make:60: recipe for target 'REFPROP.h.stamp' failed
gmake[2]: *** [REFPROP.h.stamp] Error 1
CMakeFiles/Makefile2:108: recipe for target 'CMakeFiles/REFPROP_H.dir/all' failed
gmake[1]: *** [CMakeFiles/REFPROP_H.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
gmake: *** [all] Error 2
```


But after updating numpy from 1.8.0 to 1.11.2 in python2.7,

```
Installed /usr/lib64/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg
Processing dependencies for numpy==1.11.2
Finished processing dependencies for numpy==1.11.2
```

Ran ```cmake --build . ```  and produced this result:

```
# cmake --build .
[ 93%] Built target refprop
[100%] About to build the REFPROP.h header file w/ /usr/bin/python;-u;/opt/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/opt/REFPROP-cmake/fortran/DLLFILES;--python-exe;/usr/bin/python
Writing the .pyf file with numpy.f2py, please be patient...
About to run: /usr/bin/python -m numpy.f2py --quiet --no-lower -h REFPROP.pyf /opt/REFPROP-cmake/fortran/DLLFILES/PASS_FTN.FOR
numpy version: 1.11.2
Deleting REFPROP.pyf
[100%] Built target REFPROP_H
#
```

The librefprop.so and REFPROP.h was created in the build folder. Does it mean that Refprop 10 cmake was installed successfully?

**Comment by ianhbell** [comment]
Please see this note on another of my repositories about the ``PYTHON_EXECUTABLE`` variable: https://github.com/usnistgov/CEGO#cmake-build .  If PYTHON_EXECUTABLE gets set to your python 3.4, things should work.  In the log, it will mention which version of python it found.

Often it is difficult on linux to convince tools to use the version of python you want.

In any case, looks like your python 2.7 built successfully!

**Comment by zenasc** [comment]
Great info! Thank you for your help. We greatly appreciate it!

**Comment by zenasc** [comment]
Ian,

Our user tried to run refprop 10 and got this error:

**Comment by ianhbell** [comment]
Please see fix at: https://github.com/usnistgov/CEGO#prerequisites . I assume they are using Anaconda Python?

**Comment by zenasc** [comment]
Okay, thank you. Will try the fix.
