### ISSUE TITLE
unable to call f2py

### ISSUE THREAD

**Issue by pascaltobaly** [usnistgov/REFPROP-cmake#59]
Dear Ian,
I try to build refprop to use it on linux as a backend to CoolProp

It alway fails for me
here on ubuntu 21.04 Ubuntu, it complains that it can't call f2py but numpy is well installesd on my system 
here is the trace of cmake config an build
If you have any clue...
Thanks in advance
Pascal

(base) tobaly@Bureau-NVMe:~/REFPROP-cmake/build$ cmake .. -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 10.3.0
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /usr/bin/gfortran - skipped
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 - yes
-- Found PythonInterp: /usr/bin/python3.9 (found version "3.9.5") 
-- DEFSYM_FLAG: --using-defsym
-- linux
Missing from PASS_CMN_tokens:  ['ABFLSHdll', 'ALLPROPS0dll', 'ALLPROPS1dll', 'ALLPROPS20dll', 'ALLPROPSdll', 'CRTPNTdll', 'DEFL1dll', 'DERVPVTdll', 'DHFL1dll', 'DSD1dll', 'ERRMSGdll', 'FLAGSdll', 'GERG08dll', 'GETENUMdll', 'GETMODdll', 'GETREFDIRdll', 'HEATFRMdll', 'HMXORDERdll', 'HSFL1dll', 'MASSFLUXdll', 'MELTKdll', 'PASSCMNdll', 'PEFL1dll', 'PHI0dll', 'PHIDERVdll', 'PHIHMXdll', 'PHIKdll', 'PHIMIXdll', 'RDXHMXdll', 'REFPROP1dll', 'REFPROP2dll', 'REFPROPdll', 'RIEMdll', 'SATESTdll', 'SATGUESSdll', 'SETFLUIDSdll', 'SETMIXTUREdll', 'SETREFDIRdll', 'STNdll', 'TEFL1dll', 'THFL1dll', 'TSATPdll', 'TSFL1dll', 'VIRBCDdll', 'WMOLIdll']
Missing from REFPROP_lib.h: ['DPDDKdll', 'DPDTKdll', 'ACTVYdll', 'DOTFILLdll', 'OMEGAdll', 'ETAK0dll', 'ETAK1dll', 'ETAKRdll', 'ETAKBdll', 'TCXK0dll', 'TCXKBdll', 'TCXKCdll']

-- REFPROP version <= 9.1 identified by presence of include "'commons.for'"; copying locally and fixing include statement
-- Fixing of FORTRAN files complete. Compilation ready.
-- Set REFPROP_FORTRAN_PATH to /home/tobaly/REFPROP-cmake/build/FORTRAN_temp
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tobaly/REFPROP-cmake/build

(base) tobaly@Bureau-NVMe:~/REFPROP-cmake/build$ cmake --build .
Scanning dependencies of target REFPROP_H
[  3%] About to build the REFPROP.h header file w/ /usr/bin/python3.9;-u;/home/tobaly/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/home/tobaly/REFPROP-cmake/build/FORTRAN_temp;--python-exe;/usr/bin/python3.9
Writing the .pyf file with numpy.f2py, please be patient...
About to run: /usr/bin/python3.9 -m numpy.f2py --quiet --no-lower -h REFPROP.pyf /home/tobaly/REFPROP-cmake/build/FORTRAN_temp/PASS_FTN.FOR
numpy version: 1.19.5
Writing the .pyf file with numpy.f2py, please be patient...
About to run: /usr/bin/python3.9 -m numpy.f2py --quiet --no-lower -h REFPROP.pyf /home/tobaly/REFPROP-cmake/build/FORTRAN_temp/DLLFILES/PASS_FTN.FOR
numpy version: 1.19.5
Traceback (most recent call last):
  File "/home/tobaly/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 179, in <module>
    generate_interface_file(os.path.join(args.FORTRAN_path[0],'PASS_FTN.FOR'), 'REFPROP.pyf', python_exe = args.python_exe[0])
  File "/home/tobaly/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 26, in generate_interface_file
    raise ValueError('Unable to call f2py successfully: '+str(err))
ValueError: Unable to call f2py successfully: b'Traceback (most recent call last):\n  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code\n    exec(code, run_globals)\n  File "/usr/lib/python3/dist-packages/numpy/f2py/__main__.py", line 4, in <module>\n    main()\n  File "/usr/lib/python3/dist-packages/numpy/f2py/f2py2e.py", line 694, in main\n    run_main(sys.argv[1:])\n  File "/usr/lib/python3/dist-packages/numpy/f2py/f2py2e.py", line 434, in run_main\n    postlist = callcrackfortran(files, options)\n  File "/usr/lib/python3/dist-packages/numpy/f2py/f2py2e.py", line 338, in callcrackfortran\n    postlist = crackfortran.crackfortran(files)\n  File "/usr/lib/python3/dist-packages/numpy/f2py/crackfortran.py", line 3253, in crackfortran\n    readfortrancode(files, crackline)\n  File "/usr/lib/python3/dist-packages/numpy/f2py/crackfortran.py", line 493, in readfortrancode\n    readfortrancode(fn1, dowithline=dowithline, istop=0)\n  File "/usr/lib/python3/dist-packages/numpy/f2py/crackfortran.py", line 499, in readfortrancode\n    dowithline(finalline)\n  File "/usr/lib/python3/dist-packages/numpy/f2py/crackfortran.py", line 795, in crackline\n    analyzeline(m, pat[1], line)\n  File "/usr/lib/python3/dist-packages/numpy/f2py/crackfortran.py", line 1183, in analyzeline\n    for e in markoutercomma(ll).split(\'@,@\'):\n  File "/usr/lib/python3/dist-packages/numpy/f2py/crackfortran.py", line 832, in markoutercomma\n    assert not f, repr((f, line, l))\nAssertionError: (-1, \'ncmax=20)     !max number of components in mixtur\', \'ncmax=20)     !max number of components in mixtur\')\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tobaly/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 181, in <module>
    generate_interface_file(os.path.join(args.FORTRAN_path[0],'DLLFILES','PASS_FTN.FOR'), 'REFPROP.pyf', python_exe = args.python_exe[0])
  File "/home/tobaly/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 26, in generate_interface_file
    raise ValueError('Unable to call f2py successfully: '+str(err))
ValueError: Unable to call f2py successfully: b'IOError: [Errno 2] No such file or directory: \'/home/tobaly/REFPROP-cmake/build/FORTRAN_temp/DLLFILES/PASS_FTN.FOR\'. Skipping file "/home/tobaly/REFPROP-cmake/build/FORTRAN_temp/DLLFILES/PASS_FTN.FOR".\n'
gmake[2]: *** [CMakeFiles/REFPROP_H.dir/build.make:80 : REFPROP.h.stamp] Erreur 1
gmake[1]: *** [CMakeFiles/Makefile2:97 : CMakeFiles/REFPROP_H.dir/all] Erreur 2
gmake: *** [Makefile:103 : all] Erreur 2

**Comment by ianhbell** [comment]
Looks like because you have REFPROP 9.0 it looks in the wrong place for PASS_FTN.FOR.

**Comment by ianhbell** [comment]
Better question: what version of REFPROP are you trying to compile?

**Comment by ianhbell** [comment]
I pushed a small change to fail more clearly when the path is wrong.

**Comment by pascaltobaly** [comment]
Hi  Ian,
Thanks for youir quick answer
I use REFPROP  version 9.1  updated 12/09/2013
it's rather old, I admit
There is a file named PASS_FTN.FOR in the FORTRAN directory

**Comment by ianhbell** [comment]
Something about the .FOR file causes f2py to fail. Not sure why the same doesn't happen with the .INC files of REFPROP 10.  But I think because the file extension indicates how to parse the file, and it parses them differently.
