### ISSUE TITLE
Error with cmake --build .

### ISSUE THREAD

**Issue by MitchelDaniel** [usnistgov/REFPROP-cmake#87]
Hello, I am trying to install the refprop libraries but having some error messages come up during the second cmake command.
I am running Ubuntu 20.04. I have refprop 9.1 

I will review the steps, maybe you can tell me if I did something wrong.
First of all, I believe I have all the prerequisite software installed
`pip install six
Requirement already satisfied: six in /usr/lib/python3/dist-packages (1.14.0)
`

`python3 -c "import numpy; print(numpy.__version__)"
1.17.4
`

` gfortran --version
GNU Fortran (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`

`cmake --version
cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).`

`git --version
git version 2.25.1
`
1. I did a git clone of the repository in my Downloads folder
2. Copied my fortran directory (COMMONS, etc) into the root of REFPROP-cmake folder
3/4/5. mkdir build, cd build
6. sudo cmake .. -DCMAKE_BUILD_TYPE=Release completed with no errors visible
7. sudo --build .
```[  3%] About to build the REFPROP.h header file w/ /usr/bin/python;-u;/home/mitch/Downloads/REFPROP-cmake/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/home/mitch/Downloads/REFPROP-cmake/REFPROP-cmake/build/FORTRAN_temp;--python-exe;/usr/bin/python
Writing the .pyf file with numpy.f2py, please be patient...
About to run: /usr/bin/python -m numpy.f2py --quiet --no-lower -h REFPROP.pyf /home/mitch/Downloads/REFPROP-cmake/REFPROP-cmake/build/FORTRAN_temp/PASS_FTN.FOR
numpy version: 1.16.5
Traceback (most recent call last):
  File "/home/mitch/Downloads/REFPROP-cmake/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 183, in <module>
    generate_interface_file(valid_paths[0], 'REFPROP.pyf', python_exe = args.python_exe[0])
  File "/home/mitch/Downloads/REFPROP-cmake/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 26, in generate_interface_file
    raise ValueError('Unable to call f2py successfully: '+str(err))
ValueError: Unable to call f2py successfully: Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/numpy/f2py/__main__.py", line 6, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/numpy/f2py/f2py2e.py", line 685, in main
    run_main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/numpy/f2py/f2py2e.py", line 425, in run_main
    postlist = callcrackfortran(files, options)
  File "/usr/lib/python2.7/dist-packages/numpy/f2py/f2py2e.py", line 329, in callcrackfortran
    postlist = crackfortran.crackfortran(files)
  File "/usr/lib/python2.7/dist-packages/numpy/f2py/crackfortran.py", line 3251, in crackfortran
    readfortrancode(files, crackline)
  File "/usr/lib/python2.7/dist-packages/numpy/f2py/crackfortran.py", line 495, in readfortrancode
    readfortrancode(fn1, dowithline=dowithline, istop=0)
  File "/usr/lib/python2.7/dist-packages/numpy/f2py/crackfortran.py", line 501, in readfortrancode
    dowithline(finalline)
  File "/usr/lib/python2.7/dist-packages/numpy/f2py/crackfortran.py", line 796, in crackline
    analyzeline(m, pat[1], line)
  File "/usr/lib/python2.7/dist-packages/numpy/f2py/crackfortran.py", line 1184, in analyzeline
    for e in markoutercomma(ll).split('@,@'):
  File "/usr/lib/python2.7/dist-packages/numpy/f2py/crackfortran.py", line 833, in markoutercomma
    assert not f, repr((f, line, l))
AssertionError: (-1, 'ncmax=20)     !max number of components in mixtur', 'ncmax=20)     !max number of components in mixtur')

make[2]: *** [CMakeFiles/REFPROP_H.dir/build.make:61: REFPROP.h.stamp] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/REFPROP_H.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```
What is the issue?

**Comment by MitchelDaniel** [comment]
My apologies, I didn't take a look at closed issues first. I've taken a look and it seems my issue is related to this [post](https://github.com/usnistgov/REFPROP-cmake/issues/79#issue-1643352257). I have Refprop9.1, so I will update to v10 and see if that works and update the issue appropriately.

**Comment by ianhbell** [comment]
Let's hope that sorts it out
