### ISSUE TITLE
Building REFPROP on Linuxmint 21 Cinnamon

### ISSUE THREAD

**Issue by nidingen** [usnistgov/REFPROP-cmake#94]
Hi!
Tried to build REFPROP on my Linux desktop. Istalled cmake and git, the other needed softwares were already present, incl numpy.
I get loads of warnings when compiling. This is one example,

~~~
Warning: Unused dummy argument ‘icomp’ at (1) [-Wunused-dummy-argument]
/home/martin/REFPROP-cmake/build/FORTRAN_temp/TRNS_VIS.FOR:1802:27:

 1802 |       function ETAH2 (icomp,t,d)
~~~
Only warnings so seem ok, but then I get the following error. It is somewhere in the Python. The error message is the following:
~~~
[ 96%] Linking Fortran shared library librefprop.so
[ 96%] Built target refprop
[100%] About to build the REFPROP.h header file w/ /usr/bin/python3.10;-u;/home/martin/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/home/martin/REFPROP-cmake/build/FORTRAN_temp;--python-exe;/usr/bin/python3.10
Writing the .pyf file with numpy.f2py, please be patient...
About to run: /usr/bin/python3.10 -m numpy.f2py --quiet --no-lower -h REFPROP.pyf /home/martin/REFPROP-cmake/build/FORTRAN_temp/PASS_FTN.FOR
numpy version: 1.21.5
Traceback (most recent call last):
  File "/home/martin/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 183, in <module>
    generate_interface_file(valid_paths[0], 'REFPROP.pyf', python_exe = args.python_exe[0])
  File "/home/martin/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 26, in generate_interface_file
    raise ValueError('Unable to call f2py successfully: '+str(err))
ValueError: Unable to call f2py successfully: b'Traceback (most recent call last):\n  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code\n    exec(code, run_globals)\n  File "/usr/lib/python3/dist-packages/numpy/f2py/__main__.py", line 4, in <module>\n    main()\n  File "/usr/lib/python3/dist-packages/numpy/f2py/f2py2e.py", line 692, in main\n    run_main(sys.argv[1:])\n  File "/usr/lib/python3/dist-packages/numpy/f2py/f2py2e.py", line 430, in run_main\n    postlist = callcrackfortran(files, options)\n  File "/usr/lib/python3/dist-packages/numpy/f2py/f2py2e.py", line 334, in callcrackfortran\n    postlist = crackfortran.crackfortran(files)\n  File "/usr/lib/python3/dist-packages/numpy/f2py/crackfortran.py", line 3332, in crackfortran\n    readfortrancode(files, crackline)\n  File "/usr/lib/python3/dist-packages/numpy/f2py/crackfortran.py", line 509, in readfortrancode\n    readfortrancode(fn1, dowithline=dowithline, istop=0)\n  File "/usr/lib/python3/dist-packages/numpy/f2py/crackfortran.py", line 515, in readfortrancode\n    dowithline(finalline)\n  File "/usr/lib/python3/dist-packages/numpy/f2py/crackfortran.py", line 811, in crackline\n    analyzeline(m, pat[1], line)\n  File "/usr/lib/python3/dist-packages/numpy/f2py/crackfortran.py", line 1201, in analyzeline\n    for e in markoutercomma(ll).split(\'@,@\'):\n  File "/usr/lib/python3/dist-packages/numpy/f2py/crackfortran.py", line 848, in markoutercomma\n    assert not f, repr((f, line, l))\nAssertionError: (-1, \'ncmax=20)     !max number of components in mixtur\', \'ncmax=20)     !max number of components in mixtur\')\n'
gmake[2]: *** [CMakeFiles/REFPROP_H.dir/build.make:73: REFPROP.h.stamp] Fel 1
gmake[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/REFPROP_H.dir/all] Fel 2
gmake: *** [Makefile:91: all] Fel 2
~~~
Thanks!

**Comment by ianhbell** [comment]
What version of linux? It builds fine on my side on ubuntu 22.04 and ubuntu 20.04. I use these docker containers: https://github.com/usnistgov/REFPROP-tests/tree/master/docker/test

**Comment by nidingen** [comment]
Linuxmint 21 (mentioned in the title). Did not use any dockers. Followed the instructions for cmake etc, i.e
~~~
git clone
copied FORTRAN dir from Windows installation
mkdir build
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build .
~~~
which then ended in the error message displayed in the op.

**Comment by ianhbell** [comment]
There are wayy too many linux distros to test them all. Can you use an ubuntu-based one? 

* What exact version of REFPROP?
* Did you fix the line endings for the files copied from windows?

**Comment by nidingen** [comment]
Linuxmint is Ubuntu-based (and thus Debian-based). I think Linuxmint 21 is Ubuntu 20.04 LTS.

The version of REFPROP I have is Database 23 version 9.1 (yes, old, I've had it for ages).

I had not fixed the line endings (had not used a Windows computer in a while so had forgotten...). I did so through dos2unix and the error message is the same.

Note: I have Python3 only installed. It seems fine as it calls 
~~~
About to run: /usr/bin/python3.10 -m numpy.f2py --quiet --no-lower -h REFPROP.pyf /home/nixa/REFPROP-cmake/build/FORTRAN_temp/PASS_FTN.FOR
~~~
but could this be an issue?

**Comment by ianhbell** [comment]
Weirdly numpy sometimes randomly barfs in f2py, and I haven't always been able to figure out why.  I have also done compiles on ubuntu 20.04, and that usually is flawless. Can you upgrade to version 10? That I know for sure works, as that is what I am running all my tests against.

**Comment by ianhbell** [comment]
It could be the numpy version. But it doesn't seem so straightforward, some versions work fine and others don't.  I think it really might require an upgrade to v10. I can try later on on my side in a docker container.

**Comment by ianhbell** [comment]
I can confirm this build error. You can either upgrade to REFPROP 10, or use librefprop.so: https://github.com/jowr/librefprop.so

**Comment by nidingen** [comment]
Confirm? Do not follow I am afraid... do you mean you could recreate this on version 9.1?

**Comment by ianhbell** [comment]
Yes, I get the same error.

**Comment by nidingen** [comment]
Ok, understand. Will look into librefprop.so or consider version 10. Thanks for your help.
