### ISSUE TITLE
OSX installation error:  no FORTRAN or aliases_string.txt

### ISSUE THREAD

**Issue by matlawicebox** [usnistgov/REFPROP-cmake#98]
I don't have anaconda or brew, and I'm trying to do the installation method 2 (using gcc/gfortran from Macports).  I had to install cmake which I did directly from cmake.org.  I think I'm following the instructions by doing the following (outputs included), but obviously I'm doing something wrong and I can't figure out what - I've looked online for help but nothing is coming up.  It looks to me like a) it's looking for Fortran directory (which I thought the gcc/gfortran steps were done to avoid) and it also can't find aliases_string.txt.

```
% sudo port install gcc12
Password:
--->  Computing dependencies for gcc12
--->  Cleaning gcc12
--->  Scanning binaries for linking errors
--->  No broken files found.
--->  No broken ports found.
% sudo port select gcc mp-gcc12
Selecting 'mp-gcc12' for 'gcc' succeeded. 'mp-gcc12' is now active.
```
The instructions say I can now use the non-Mac instructions listed above (except I'm assuming not the bit about Fortran directory from REFPROP installation since that doesn't exist in Mac).  So then I do the cloning:
```
%git clone --recursive https://github.com/usnistgov/REFPROP-cmake.git
```
Then I go to the REFPROP-cmake directory and do the following:
```
% cd build
% /Applications/CMake.app/Contents/bin/cmake .. -DCMAKE_BUILD_TYPE=Release
```
which gives me the following output with error message:
```
CMake Warning (dev) at CMakeLists.txt:6 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- DEFSYM_FLAG: 
-- Alias generation output: darwin

-- Alias generation error: Traceback (most recent call last):
  File "/Users/matlawicebox/Desktop/REFPROP-cmake/generate_aliases.py", line 22, in tokenize
    for line in open(os.path.join(path_to_FORTRAN,"PASS_FTN.FOR"), 'r').readlines():
FileNotFoundError: [Errno 2] No such file or directory: '/Users/matlawicebox/Desktop/REFPROP-cmake/FORTRAN/PASS_FTN.FOR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/matlawicebox/Desktop/REFPROP-cmake/generate_aliases.py", line 129, in <module>
    tokens = tokenize(header_path, FORTRAN_path)
  File "/Users/matlawicebox/Desktop/REFPROP-cmake/generate_aliases.py", line 25, in tokenize
    for line in open(os.path.join(path_to_FORTRAN,"DLLFILES","PASS_FTN.FOR"), 'r').readlines():
FileNotFoundError: [Errno 2] No such file or directory: '/Users/matlawicebox/Desktop/REFPROP-cmake/FORTRAN/DLLFILES/PASS_FTN.FOR'

CMake Error at CMakeLists.txt:174 (file):
  file failed to open for reading (No such file or directory):

    /Users/matlawicebox/Desktop/REFPROP-cmake/build/aliases_string.txt


-- Path to libquadmath.a:/opt/local/lib/gcc12/gcc/arm64-apple-darwin23/12.3.0/../../../libquadmath.a
-- Copied libquadmath.a here.
-- Configuring incomplete, errors occurred!

```

**Comment by ianhbell** [comment]
It seems like you didn't install REFPROP? Otherwise, setting the ``-DREFPROP_FORTRAN_PATH=...`` is recommended.

**Comment by matlawicebox** [comment]
Ah, it wasn't clear to me that I had to install on a Windows machine and then copy folders from that over to my Mac.  Thx.

**Comment by ianhbell** [comment]
You can also ask us for a zip of the sources, but your method is better generally.
